name: narrativia
description: NarrativIA app

publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
